--- 
title: "Analyzing emotions towards Elon Musk on Twitter "
author: "Anni Chen, Zehui Wu, Senqi Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Elon Musk, a well-known entrepreneur and business magnate who founded Paypal, SpaceX and Tesla Motors, taken back the title of the world's richest person in December 2021 with an estimated net worth of around US$265 billion. Besides all those miracles and innovations he made in his business empire, he forms a controversial figure on the Internet, especially with his appealing words on Twitter. Till Dec. 2021, he has owned 65.6M followers on Twitter as his 13th year of creating account. There's no doubt that Elon Musk is quite a social media influencer who tweets frequently everyday and expresses opinions on a variety of topics including: spaceX, crypto-currency, Tesla, etc.. Twitter users always have heated discussions surrounding his tweets and associated actions. Based on those facts, we are curious about how people commenting on Elon Musk's Tweets. After applying several techniques suc like NLP, we want to visualize user discussions on related topics and explore underlying patterns.

In the project, we collected Twitter streaming data using Tweepy API for a continuous week starting from Nov. 28,2021. The tweets collected will be json objects and there will be a lot of features included. NLP techniques will be applied to calculate the sentiments and classify topics on ??tweet/extended_tweet?? feature. Other features like ??user??, ??timestamp??, ??follower_count??, will also contribute to our analysis. We consider to carry out analysis at both tweet level and user level and hopefully the geographic and time series information can help answer the following questions:

-What's the volumes of users' retweet on Elon Musk's tweet over time?
-What's the geo information can we get from the users' retweet?
-Any other distribution of the characteristics of the followers/ people making comments?
-What are the most popular topics/the most frequent words in tweets about Elon Musk? What are the most frequently mentioned topics in tweets of negative or positive sentiment?
-For each individual topic, what is the distribution of sentiments and what are the most frequent words?
-Trends on real-time public opinion rate on keywords over time. Whether sentiments from mainstream media have a larger influence on it?

